theme: jekyll-theme-slate
title: NEOTOMA STUDIOS SHIT SITE
description: f you github pages
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
